version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-docker
    ports:
      - "3000:3000"
    volumes:
      - /storage:/app
    environment:
      MODE_ENV: development
      DATABASE_URL: 0
    depends_on:
      - db

  db:
    image: mongo:6
    ports:
      - "27017:27017" # Map port cho MongoDB (tùy chọn)
    volumes:
      - db_data:/data/db # Lưu trữ dữ liệu MongoDB
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nestjs.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt  
    depends_on:
      - app
volumes:
  db_data: # Volume cho MongoDB
